// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDERD-qFSh69rn6nwBzUE8J7Oz1_oRQuec',
    appId: '1:43302187180:web:884a022e4fce3b9fc2ef09',
    messagingSenderId: '43302187180',
    projectId: 'auth-c7409',
    authDomain: 'auth-c7409.firebaseapp.com',
    storageBucket: 'auth-c7409.appspot.com',
    measurementId: 'G-Z51DP3WJ9F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD29nWBIW_DTPVzda-W7FXv0VE1xWnbNaA',
    appId: '1:43302187180:android:37be9b12568d0cb5c2ef09',
    messagingSenderId: '43302187180',
    projectId: 'auth-c7409',
    storageBucket: 'auth-c7409.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4SGUi3GVjzIqeVjWn1JZwjw21l5b3-bE',
    appId: '1:43302187180:ios:3d7929e91fe77fefc2ef09',
    messagingSenderId: '43302187180',
    projectId: 'auth-c7409',
    storageBucket: 'auth-c7409.appspot.com',
    iosBundleId: 'com.example.auth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4SGUi3GVjzIqeVjWn1JZwjw21l5b3-bE',
    appId: '1:43302187180:ios:fed6f378a9f99682c2ef09',
    messagingSenderId: '43302187180',
    projectId: 'auth-c7409',
    storageBucket: 'auth-c7409.appspot.com',
    iosBundleId: 'com.example.auth.RunnerTests',
  );
}
